- .github/workflows/integration.yaml
- bundle.yaml
- charms/mlflow-server/files/mlflow_requirements.txt
- charms/mlflow-server/metadata.yaml
- charms/mlflow-server/src/charm.py
It uses an older Prometheus charm that is deprecated in favor of
https://charmhub.io/prometheus-k8s
> Remove prometheus relation

- charms/mlflow-server/metadata.yaml
This PR addresses https://github.com/canonical/bundle-kubeflow/issues/425 where a PVC is created per operator, adding the `min-juju-version: 2.9.0` element to prevent that PVC creation.
> Add min-juju-version element to prevent excess PVC creation

- .github/workflows/integration.yaml
- charms/mlflow-server/src/charm.py
- tests/test_selenium.py
fixes canonical/bundle-kubeflow#436
This fixes the istio ingress/virtualservice routing.  
Previously, the rewrite rule of `prefix=/mlflow` would serve a blank page at `INGRESS/mlflow` and a dead link at `INGRESS/mlflow/.  This appeared to be because the rewrite rules would break the static files that mlflow serves.  With this old rule (no trailing slash in the prefix) the static files get served at `INGRESS/static-files/...` rather than `INGRESS/mlflow/static-files/...` and are thus inaccessible.  
With this PR, the rewrite rule of `prefix=mlflow/` (including trailing slash) serves the correct mlflow UI at `INGRESS/mlflow/` with the static files correctly being accessed from `INGRESS/mlflow/static-files/...`.  But, this serves nothing at `INGRESS/mlflow`, which might be counter …
> fix: add trailing '/' to uri in ingress

- charms/mlflow-server/src/charm.py
Update the CheckFailedError to use the self.msg, which is a string
instead of using the "msg" class on the status_type class.
> Use str instead of NoVersionsListed class

- charms/mlflow-server/requirements.txt
- charms/mlflow-server/src/charm.py
- charms/mlflow-server/tests/test_charm.py
Fixes #26.  Charm creates a secret with mlflow's s3 credentials called  `{charm_name}-seldon-init-container-s3-credentials`.  This secret is formatted as needed for a [Seldon Deployment Init Container](https://docs.seldon.io/projects/seldon-core/en/latest/servers/kfserving-storage-initializer.html#create-a-secret-containing-the-environment-variables).
Also:
* adds tests for the new secret
* refactors some secret creation to make the main function of the charm read easier
* removes an unused dependency from requirements.txt
> feat: Add a secret to use with seldon deployments

- .github/workflows/release.yaml
Temporarily pins `release-charm` action pinned to a development version to handle charmhub branches.  See #39 for more information.
> hack: pin `release-charm` action to dev version

- .github/workflows/integrate.yaml
- charms/mlflow-server/lib/charms/grafana_k8s/v0/grafana_dashboard.py
- charms/mlflow-server/lib/charms/observability_libs/v0/juju_topology.py
- charms/mlflow-server/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- charms/mlflow-server/requirements.txt
- charms/mlflow-server/src/charm.py
- charms/mlflow-server/test-requirements.txt
- charms/mlflow-server/tests/integration/test_charm.py
- charms/mlflow-server/tests/unit/__init__.py
https://github.com/canonical/bundle-kubeflow/issues/429
Summary of changes:
- Added namespace to endpoint URL encoding.
- Added integration testing.
> Bug: MLFlow Seldon secrets is incorrectly formatted.

- charms/mlflow-server/metadata.yaml
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
> feat: localize SDI schemas

- CONTRIBUTING.md
The contributing file seems to have been just directly copied from [training operator contributing file](https://github.com/canonical/training-operator/blob/main/CONTRIBUTING.md).
Made some tweaks to the file to make it more specific to MLFLow.
> KF-3635 contributing updates

- src/charm.py
- src/secrets/mlflow-seldon-rclone-secret.j2
Rename the fields provided in the `rclone` Secret to match the names that the Seldon storage initializer expects.
Closes #182
> fix: Rename `seldon-rclone-secret` fields

- src/secrets/mlflow-seldon-rclone-secret.j2
According to the [Seldon docs](https://docs.seldon.io/projects/seldon-core/en/v1.14.0/servers/overview.html#example-minio-configuration), `RCLONE_CONFIG_S3_ENV_AUTH` receives a boolean value. However, passing `true` or `false` will cause the metacontroller to break when attempting to convert the Secret from JSON to a Go struct, since it's unable to unmarshall the boolean field. This in turn, will lead to the secret not being applied.
Consequently, we have to quote the boolean value to ensure it's interpreted as a string, e.g.
```yaml
RCLONE_CONFIG_S3_ENV_AUTH: "false"
```
> fix: Pass `ENV_AUTH` value as string

- tests/integration/test_charm.py
Test charm with mysql 8.0/stable
> Test mysql 8.0/stable

- tools/get-images.sh
closes #210 
```bash
bash tools/get-images.sh
docker.io/ubuntu/mlflow:2.1.1_1.0-22.04
docker.io/charmedkubeflow/mlflow-prometheus-exporter:1.0-22.04
```
> feat: get images on track/2.1

- releases/2.1/beta/mlflow/bundle.yaml
- releases/2.1/edge/mlflow/bundle.yaml
- releases/2.1/stable/mlflow/bundle.yaml
- releases/latest/beta/mlflow/bundle.yaml
- releases/latest/edge/mlflow/bundle.yaml
- releases/latest/stable/mlflow/bundle.yaml
- tests/integration/test_charm.py
> fix: use mysql-k8s `8.0/edge` in the integration tests and bundles

- releases/2.1/beta/mlflow/bundle.yaml
- releases/2.1/edge/mlflow/bundle.yaml
- releases/2.1/stable/mlflow/bundle.yaml
- releases/latest/beta/mlflow/bundle.yaml
- releases/latest/edge/mlflow/bundle.yaml
- releases/latest/stable/mlflow/bundle.yaml
- tests/integration/test_charm.py
backports 270dff3fa97142a53de98bec75c16f77750d1de3 to `track/2.1`
* fix: use mysql-k8s edge
* fix: add comment to revert to stable
> fix: use mysql-k8s `8.0/edge` in the integration tests and bundles (#225)

- .github/workflows/integrate.yaml
- releases/2.1/beta/mlflow/bundle.yaml
- releases/2.1/edge/mlflow/bundle.yaml
- releases/2.1/stable/mlflow/bundle.yaml
- releases/latest/beta/mlflow/bundle.yaml
- releases/latest/edge/mlflow/bundle.yaml
- releases/latest/stable/mlflow/bundle.yaml
- tests/integration/test_charm.py
backports ed3621b453737483355a6c7e47abc941ee677080 and 270dff3fa97142a53de98bec75c16f77750d1de3
closes #224 and addresses https://github.com/canonical/bundle-kubeflow/issues/813 in branch `track/2.1`
CI is failing due to #232, this PR is pointed to a dev branch so we can fix this issue next.
> fix: backport CI fixes to track/2.1

- tests/integration/test_charm.py
closes #232 
targeted at branch `track/2.1`
> fix: dependency charm channels in integration tests

- .github/workflows/integrate.yaml
- releases/2.1/beta/mlflow/bundle.yaml
- releases/2.1/edge/mlflow/bundle.yaml
- releases/2.1/stable/mlflow/bundle.yaml
- releases/latest/beta/mlflow/bundle.yaml
- releases/latest/edge/mlflow/bundle.yaml
- releases/latest/stable/mlflow/bundle.yaml
- tests/integration/test_charm.py
merges the fixes of https://github.com/canonical/bundle-kubeflow/issues/813, https://github.com/canonical/mlflow-operator/issues/224, and https://github.com/canonical/mlflow-operator/issues/232 to `track/2.1`
> fix: merge dev branch to fix CI issues

- tests/integration/test_charm.py
In 8.0/edge a strict  was introduced, making this charm impossible to deploy with a juju version == 3.5.{0,1}. Since this version is the one we use in our CI, we have to pin mysql-k8s to its stable version as it does not have these restrictions.
> tests: use mysql-k8s from 8.0/stable instead of 8.0/edge

- .github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
> ci: use 3.4/stable instead of 3.5/stable

- tests/integration/test_charm.py
In 8.0/edge a strict  was introduced, making this charm impossible to deploy with a juju version == 3.5.{0,1}. Since this version is the one we use in our CI, we have to pin mysql-k8s to its stable version as it does not have these restrictions.
> tests: use mysql-k8s from 8.0/stable instead of 8.0/edge (#243)

- metadata.yaml
- tests/integration/test_charm.py
Closes: https://github.com/canonical/mlflow-operator/issues/252
- Update the MLflow image to 2.15.1
- Use minio ckf-1.19
I have also deployed manually and made sure the dashboard is accessible
> Use v2.15 image

- docs/.wordlist.txt
- docs/tutorial/mlflow-kubeflow.rst
- docs/tutorial/mlflow.rst
Closes: https://github.com/canonical/mlflow-operator/issues/245, https://github.com/canonical/mlflow-operator/issues/254, https://github.com/canonical/kserve-operators/issues/262
Changes:
- MLflow guide 
- MLflow + Kubeflow guide
```
cd docs 
make run
```
> Update docs for 2.15

- docs/how-to/index.rst
- docs/how-to/migrate-v21-v215.rst
- docs/reuse/links.txt
Closes: https://github.com/canonical/mlflow-operator/issues/256
> Upgrade guide for 2.15

- .github/workflows/integrate.yaml
- .gitignore
- terraform/README.md
- terraform/main.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform/versions.tf
- tox.ini
This commit adds the terraform/ directory to the root of the repository to host the Terraform module of this charm. This follows the standard set in CC006. For more information please also refer to canonical/argo-operators/pull/198.
Fixes #266
1. Check the correctness of the module with `tox -e tflint`
2. Apply with `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve`
3. Wait for the charm to be deployed.
This module must expose all the information in the `metadata.yaml` of this charm, make sure you review it by comparing that file to the Tf files in this PR.
> feat: add Terraform module for mlflow-server

- .github/workflows/integrate.yaml
- terraform/README.md
This PR introduces the following changes based on a recent update to the team's standards for the terraform charm modules:
* docs: remove compatibility note
The latest standard for the terraform/ README.md is that the compatibility
note can be obviated since the module at the branch is compatible with the
charm in the same branch.
* ci: remove the channel from terraform checks
Since the default for deploying the charm is now set to latest/edge in
the re-usable workflow, this is not required anymore.
Part of #266 (even though it was already closed)
> ci, docs: update to match standards for terraform

- charmcraft.yaml
- lib/charms/loki_k8s/v1/loki_push_api.py
- metadata.yaml
- requirements-unit.txt
- requirements.in
- requirements.txt
- src/charm.py
- terraform/outputs.tf
- tests/integration/test_charm.py
- tests/integration/test_deploy_runners.py
- tests/unit/test_operator.py
Add log forwarding from mlflow-server to Loki, using Pebble feature, which is configured by `loki_k8s.v1.loki_push_api.LogForwarder`.
How I tested it:
```bash
juju add-model mlflow
juju deploy mlflow --channel=2.15/stable --trust
charmcraft pack
juju refresh mlflow-server --path ./mlflow-server_ubuntu-20.04-amd64.charm
juju deploy grafana-agent-k8s --channel edge
juju consume u2-k8s:cos.loki-logging  # u2-k8s is constoller and cos is model name
juju integrate loki-logging grafana-agent-k8s
juju integrate grafana-agent-k8s mlflow-server:logging
```
> Add logging relations

- docs/how-to/deploy-eks.rst
- docs/how-to/deploy-mlflow-kubeflow-eks.rst
Fix EKS creation guide broken link by replacing with a link to the discourse post.
> docs: Fix EKS broken link

- lib/charms/resource_dispatcher/v0/kubernetes_manifests.py
This repository contained a version of the kubernetes_manifestss lib that was not exactly the one that was published in Charmhub. This caused issues when trying to fetch new versions of the library.
This commit replaces the offending file with the library that is actually published.
Part of canonical/bundle-kubeflow#1209
> fix: fetch kubernetes_manifests lib with charmcraft to match published lib

- .github/workflows/integrate.yaml
Old 1.1.0 verion presents bug documented in #307. Since the action is not publishing version, use it from `main`, as we do in the rest of charm repos.
Close #307
Note that documentation checks should be fixed in #309
> fix(ci): Use actions-operator from `main`

- docs/how-to/deploy-ck8s-aws.rst
- docs/how-to/integrate-ml-ckf-ck8s.rst
Update references to broken link for Charmed Kubernetes. This resolves the error seen below
```bash
(how-to/deploy-ck8s-aws: line   10) broken    https://ubuntu.com/kubernetes/charmed-k8s - 404 Client Error:  for url: https://ubuntu.com/kubernetes/charmed-k8s
```
> fix(docs): update link to charmed kubernetes

- docs/how-to/manage/upgrade/migrate-v21-v215.rst
- releases/2.22/edge/mlflow/bundle.yaml
- releases/2.22/edge/mlflow/charmcraft.yaml
- releases/2.22/stable/mlflow/bundle.yaml
- releases/2.22/stable/mlflow/charmcraft.yaml
- releases/latest/beta/mlflow/bundle.yaml
- releases/latest/edge/mlflow/bundle.yaml
- releases/latest/stable/mlflow/bundle.yaml
- tox.ini
Closes #326
This PR:
- Creates the necessary files for the `2.22/edge`, `2.22/beta`, `2.22/stable` bundles
- Updates the bundles for `latest/edge` and `latest/stable` bundles.
- Update the `tox` bundle environments to the latest version.
- Replaces a broken link in the documentation (necessary for the documentation checks to pass).
> feat: Add `2.22` bundle for `mlflow`

- docs/.wordlist.txt
- docs/custom_conf.py
- docs/how-to/manage/upgrade/index.rst
- docs/how-to/manage/upgrade/migrate-v21-v215.rst
- docs/how-to/manage/upgrade/migrate-v215-v222.rst
- docs/index.rst
- docs/tutorial/mlflow-kubeflow.rst
- docs/tutorial/mlflow.rst
Closes #332
This PR:
- Updates the 2 main tutorial pages for `2.22`.
- Creates a new migration guide for `2.15` to `2.22`.
For https://documentation.ubuntu.com/charmed-mlflow/tutorial/mlflow/:
- Removed the `Component` table in the beginning (I don't think it makes much sense since it is only one component).
- Updated versions of Juju, microk8s, mlflow-bundle.
- Tried to remove the conversationalist style from the previous writers.
- Changed the installation of `microk8s` from `strict` to the `classic` confinement. This is similar to what we already do with `kubflow`.
- Tried to match the style we use in https://charmed-kubeflow.io/docs/get-started.
For https://documentation.ubuntu.com/charmed-mlflow/tutorial/mlflow-kubeflow/:
- Update the Ubuntu base requirement and removed the …
> chore: Update tutorials for `2.22`

- docs/.sphinx/requirements.txt
- docs/custom_conf.py
- docs/reuse/links.txt
Causes documentation to deploy a sitemap using the sphinx-sitemap extension for documentation discovery from the parent project.
> docs: Enabling sitemaps

- docs/how-to/integrate/integrate-cos.rst
Add the missing COS relations for MLflow's mysql and minio in the how to guide
> fix: add mysql and minio Observability relations to Integrate with COS guide

- docs/conf.py
- docs/how-to/manage/upgrade/migrate-v21-v215.rst
- docs/how-to/manage/upgrade/migrate-v215-v222.rst
- docs/index.rst
This is required for the `notfound` extension to function correctly and render a valid page on encountering a 404 error.
Addresses the issue raised [here](https://chat.canonical.com/canonical/pl/z435uy16k3yp8x6z3zhuamupky) in the mm docs channel.
> docs: Configure slug
