canonical/mlflow-operator

.github/workflows/integration.yaml
charms/mlflow-server/charmcraft.yaml
charms/mlflow-server/metadata.yaml
charms/mlflow-server/src/charm.py
charms/mlflow-server/tests/test_charm.py

To comply with the standard for status handling.

Small refactor to improve status handling

---

charms/mlflow-server/lib/charms/observability_libs/v0/juju_topology.py
charms/mlflow-server/lib/charms/prometheus_k8s/v0/prometheus_scrape.py

git-xargs programmatic pull request

chore: bump all charm libs

---

charms/mlflow-server/tox.ini

Pin python-libjuju to avoid CI issues

build: update python-libjuju pin to 3.0

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
charms/mlflow-server/tox.ini
renovate.json
tox.ini

Pin `runs-on` to `ubuntu-20.04` in every action. `latest` now points to `22.04`

Pin to ubuntu-20.04 for CI

---

charms/mlflow-server/src/charm.py
charms/mlflow-server/tests/unit/test_operator.py

https://github.com/canonical/mlflow-operator/issues/77
Add namespace to service.

Fix service with namespace

---

charms/mlflow-server/src/charm.py
charms/mlflow-server/src/services/s3.py
charms/mlflow-server/tests/unit/test_operator.py

Summary of changes:
- Added comments to S3 service code to clarify the usage.
- Added unit test to ensure that S3 URL endpoint is generated correctly in S3 service and in charm code.

fix: added unit test and updated comments

---

tox.ini

git-xargs programmatic pull request

fix: replace whitelist_externals with allowlist_externals

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Add integration tests for mysql.

KF-1093 Mysql integration

---

actions.yaml
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Add action for minio credentials

KF-1003 action for minio credentials

---

metadata.yaml

Use rock instead of docker image

KF-2356 Use Rock

---

metadata.yaml

Added proper doc description
Took couple of lines from Discourse
This is just a temporary measure
Excpect Discourse doc to override this when ready

Added Doc description

---

renovate.json

KF-3652 Set Renovate schedule

---

config.yaml
metadata.yaml
src/charm.py
tests/integration/test_charm.py
tests/integration/test_deploy_runners.py
tests/unit/test_operator.py

Integrate prometheus exporter with mlflow-server as second container.

KF-3620 custom Prometheus exporter 

---

renovate.json

* Use preset from https://github.com/canonical/charmed-kubeflow-workflows
PLEASE first merge this PR https://github.com/canonical/charmed-kubeflow-workflows/pull/14

KF-3652 use renovate preset

---

metadata.yaml
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

KF-3793 Add istio relation

---

.github/cluster.yaml
.github/scripts/delete_volumes.py
.github/workflows/delete-aws-volumes.yaml
.github/workflows/deploy-eks.yaml

* Run the eks CI biweekly 
* Remove volume at the end of ekc ci run 
* Set correct env variables in repo 
Successful test run in private repo here https://github.com/misohu/charmed-mlflow-eks-ci/actions/runs/5876696690

Run EKS CI biweekly and add remove volumes job

---

docs/how-to/deploy-ck8s-aws.rst
docs/how-to/deploy-kubeflow-mlflow-ck8s-aws.rst
docs/how-to/index.rst

* Add docs on how to integrate MLflow with Kubeflow on Charmed k8s.
I am referencing this guide which needs to be checked and published before this PR https://discourse.charmhub.io/t/deploying-charmed-kubeflow-to-charmed-kubernetes-on-aws/11667

Kf 1022 deploy mlflow kubeflow ck8s

---

docs/.wordlist.txt
docs/how-to/index.rst
docs/how-to/integrate-notebook.rst

[Doc Preview](https://canonical-ubuntu-documentation-library--204.com.readthedocs.build/charmed-mlflow/en/204/how-to/integrate-notebook/)

MLFlow Notebook Integration

---

CONTRIBUTING.md
docs/.wordlist.txt
docs/contributing.md
docs/explanation/index.rst
docs/explanation/why-charmed.rst
docs/index.rst

Preview: https://canonical-ubuntu-documentation-library--203.com.readthedocs.build/charmed-mlflow/en/203/explanation/why-charmed/

Kf 4301 charmed vs upstream and KF-4298 Contributing

---

README.md
docs/explanation/why-charmed.rst

Resolves this https://github.com/canonical/mlflow-operator/issues/208

Fix README.md in repo

---

lib/charms/resource_dispatcher/v0/kubernetes_manifests.py
metadata.yaml
src/charm.py
tests/unit/test_operator.py

feat: use library for secrets and pod-defaults relations

---

.github/workflows/integrate.yaml

Part of canonical/bundle-kubeflow#944

ci: bump juju 3.1/stable -> 3.4/stable in track

---

charmcraft.yaml
lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
terraform/outputs.tf
tests/integration/test_charm.py
tests/integration/test_deploy_runners.py
tests/unit/test_operator.py

* Add logging relation and define log forwarding
Add logging relation to mlflow-server to enable log forwarding to Loki.
* Fix snap build and missing requirements
* Add logging relation to TF output
backport: #277

chore(backport): Add logging relations

---

docs/tutorial/mlflow-kubeflow.rst

docs: broken link fix

---

docs/how-to/index.rst

Updating copyright year to 2025. Any change in the docs will automatically trigger this update.

[docs] Update copyright year to 2025

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
lib/charms/observability_libs/v1/kubernetes_service_patch.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
requirements-unit.txt
requirements.txt

* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184

chore: bump libraries

---

.github/workflows/integrate.yaml

adds a step to always collect charm debug artifacts after integration tests run.

feat: collect charm debug artifacts in integration tests

---

requirements-integration.in
requirements-integration.txt
requirements-unit.txt
requirements.in
requirements.txt

This PR updates charmed_kubeflow_chisme to fix https://github.com/canonical/charmed-kubeflow-chisme/issues/155

chore: Update `charmed_kubeflow_chisme` in requirements
